services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src  # Monta solo la carpeta src
    environment:
      - DB_HOST=mysql
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_NAME=${DATABASE_NAME}
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3307:3306"  # Puerto externo:interno
    volumes:
      - db-data:/var/lib/mysql
      - ./src/database/proyectoweb_users.sql:/docker-entrypoint-initdb.d/proyectoweb_users.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db-data:

networks:
  app-network:
    driver: bridge